- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Ensure hostname set
    hostname: name={{ inventory_hostname }}
    when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

  - name: update host file
    lineinfile:
       dest: /etc/hosts
       regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
       line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
       state: present
    become: yes
    with_items: "{{ groups.all }}"

